### ISSUE TITLE
SHARED_GAUGENAIK used twice

### ISSUE THREAD

**Issue by haitaoshu** [LatticeQCD/SIMULATeQCD#108]
SHARED_GAUGENAIK is used twice in condensate.h and hisqForce.h. That results in not correctly storing the final results for Naik in the smearing. It does its last operation from this shared gauge field into itself, which results in one parity being wrong.

**Comment by dbollweg** [comment]
Someone please write a proper test to show this behavior because using it twice is exactly the point of the memory sharing option in the fields...

**Comment by dbollweg** [comment]
It was indeed a problem in the on-line psibar-psi measurement, i opened a pr for the fix  #109 . The shared memory feature is used as intended in the force and smearing though.
