### ISSUE TITLE
Remove Microtimer

### ISSUE THREAD

**Issue by lukas-mazur** [LatticeQCD/SIMULATeQCD#13]
We should remove the microtimer, since it doesn't work on gpu kernel and we have the gpuStopWatch.

**Comment by luhuhis** [comment]
This is related to #3

**Comment by lukas-mazur** [comment]
MicroTimer and CudaStopWatch have been replaced by StopWatch in commit c00eec4bb496f9c52748b3e957c447e17a79cdfe
