### ISSUE TITLE
parameter file comments

### ISSUE THREAD

**Issue by clarkedavida** [LatticeQCD/SIMULATeQCD#147]
i am working with people who doesn't know ahead of time what all the parameters mean in some of the parameter files. i need to update them to be more friendly for users who are starting from nearly zero knowledge

**Comment by vishalrao009** [comment]
I am trying to generate the rational approximation file for some 2+1 flavor quarks. I would like to know what is preconditioning mass for strange and light quarks. Here is the "Input.dat" file for generating rational_approximation.rat file:
`
 2                                    
                                       
  3                                    
  0                                    
  0                                    
  0.0783706                                    
  14                                    
  12                                    
  0.00614195094436                                    
  5.0                                    
  160                                    
                                       
  2                                    
  -2                                    
  0.01508242900218416                                    
  0.0029026                                    
  14                                                          
  12                                                          
  8.42508676e-06                                              
  5.0                                                         
  160     
`

Here I am using preconditioning mass as sqrt(m_s*m_l). is it correct? also for psf2 we have m_preq=0; (why is it so), 

Running './ratApprox  Input.dat' was printing some standard errors which were bigger than requirement of 10^{-16}. I am pasting the standard errors:
'
# New rational function                                 
  # Approximation bounds are [6.141951e-03,5.000000e+00]                         
  # Precision of arithmetic is 160                                                                   
  # Degree of the approximation is (12,12)                           
  # Approximating the function (x+4*0.000000^2)^(3.000000/4.000000) (x+4*0.078371^2)^(0.000000/4.       000000) (x+4*0.000000^2)^(0.000000/4.000000) (x+4*0.000000^2)^(0.000000/4.000000)               
  # Converged at 578 iterations, error = 1.418088e-11                                         
  #-----------------------------------------------------------------------------------         
  #  r_bar_1f                                                                                  
  #-----------------------------------------------------------------------------------         
                                                                                       
  # real r_bar_1f_const, r_bar_1f_num[r_high_order_2f], r_bar_1f_den[r_high_order_2f]              
  r_bar_1f_const = 8.9904320728147035e-03                           
  r_bar_1f_num[0] = 1.4667443477677822e-01    

'

Could you describe what kind of error this is? I had to increase the precision to 160 even for psf2. (from 50 to 160 but still the errors are exactly the same).

**Comment by clarkedavida** [comment]
improvements to documentation:
- [ ] explain in more detail the purpose of the container and how it should be used
- [ ] some examples on how to use already-compiled code (tutorial)?

**Comment by clarkedavida** [comment]
more or less taken care of here: https://github.com/LatticeQCD/SIMULATeQCD/pull/151
