### ISSUE TITLE
Is CPU branch available？

### ISSUE THREAD

**Issue by MiyaaL** [LatticeQCD/SIMULATeQCD#157]
I browsed the code and found that there is a CPU (offdevice) branch, and I tried to modify the logic of the code to run the CPU branch, but it seems like that the "rhmc test" result is inconsistent with the GPU version. Is this branch currently available?

**Comment by dbollweg** [comment]
In general, setting onDevice = false should work for most basic operations, though it is only implemented to aid debugging efforts and not all modules were written with onDevice = false in mind. The rhmc class in particular has not been tested with onDevice = false, so I cannot guarantee it handling it properly

**Comment by clarkedavida** [comment]
i don't think anything else will be done in this direction, so i'm going to close this issue
