### ISSUE TITLE
toplology.cu is slow to compile

### ISSUE THREAD

**Issue by clarkedavida** [LatticeQCD/SIMULATeQCD#36]
As it says in title. In particular on Juwels it takes more than 30 mins with

module load CUDA/11.0
module load GCC/9.3.0
module load OpenMPI/4.1.0rc1
module load CMake/3.18.0

I will update with a more precise time whenever it finishes compiling.

**Comment by lukas-mazur** [comment]
This is solved by using a CUDA version >= 11.4.
