### ISSUE TITLE
StopWatch crashes program without warning when constructed before CommunicationBase

### ISSUE THREAD

**Issue by clarkedavida** [LatticeQCD/SIMULATeQCD#40]
Both ColorElectricCorrTest and hisqSmearingMultiCreate fail with this error

FATAL: [Rank 1] A CUDA error occured: performFunctor: Failed to launch kernel: invalid resource handle ( cudaErrorInvalidResourceHandle )

Can someone who knows more about this please fix it?

**Comment by dbollweg** [comment]
It seems to be that StopWatch that is causing this problem. hisqSmearingMultiCreate works if StopWatch is removed.

**Comment by luhuhis** [comment]
Some thoughts:
Should we add this piece of information to the documentation somewhere? Or is it possible to add functionality to the stopwatch that checks whether a commbase has been constructed before? Maybe make commbase a required dummy function argument to the stopwatch?

**Comment by luhuhis** [comment]
One could simply omit the parameter name to not trigger an "unused parameter" warning, and add a comment somewhere around there explaining it or so:
void myfunc(int a, double b, CommunicationBase)
{ ... }

**Comment by lukas-mazur** [comment]
It's fixed with commit d2e8a9033f495126004ef652b2ecdfdf53447634 .
If someone initializes the StopWatch before commbase, then a error message will inform you that you shouldn't do that.
This is good enough.
