### ISSUE TITLE
Mixed Precision Inverter Test fails

### ISSUE THREAD

**Issue by clarkedavida** [LatticeQCD/SIMULATeQCD#41]
It fails with:

\# [2022-01-03 01:18:46] INFO: CG: # iterations 855 residual: nan
\# [2022-01-03 01:18:46] INFO: dot1 (7.46447e+13,0) dot2 (1.25874e+07,0)
^[[1;31m# [2022-01-03 01:18:46] FATAL: [Rank 1] Inverter test failed!^[[0m
\# [2022-01-03 01:18:46] INFO: 5.93011e+06
\# [2022-01-03 01:18:46] INFO: relative error of (D^+D) * (D^+D)^-1 * phi - phi : 5.93011e+06
\# [2022-01-03 01:18:46] INFO: Time for inversion: 20.546s
^[[1;31m# [2022-01-03 01:18:46] FATAL: [Rank 0] Inverter test failed!^[[0m
^[[1;31m# [2022-01-03 01:18:46] FATAL: [Rank 3] Inverter test failed!^[[0m
^[[1;31m# [2022-01-03 01:18:46] FATAL: [Rank 2] Inverter test failed!^[[0m

Maybe Dennis can look into it?

**Comment by dbollweg** [comment]
fixed
