### ISSUE TITLE
gauge_file and Gaugefile?

### ISSUE THREAD

**Issue by clarkedavida** [LatticeQCD/SIMULATeQCD#61]
Can someone please tell me the difference between `gauge_file` in `rhmcParameters.h` and `GaugefileName` in `latticeParameters.h`? If these are the same, one should be removed. If these are different, they should be renamed...

**Comment by lukas-mazur** [comment]
Indeed, we have two different names for the same thing. I agree, they should be renamed..

**Comment by clarkedavida** [comment]
I would recommend that we use `GaugefileName` instead of `gauge_file`, since `rhmcParameters` inherits from `latticeParameters`. I guess some people using `gauge_file` in their scripts will suffer, but people using `Gaugefile` would have suffered if we made the other decision.

**Comment by clarkedavida** [comment]
OK I now see the difference. `GaugefileName` is when you have the entire gauge field name to read in, and `gauge_file` is rather just a prefix like `l366f21b6170m00336m0908_s0.` where someone can put a configuration number at the end.

In that sense `gauge_file` makes sense but it is just poorly named. I think for now I'm going to just rename it to something like `gaugeFilePrefix` or something in the code, leaving it as `gauge_file` in the parameters so scripts don't have to change.

**Comment by clarkedavida** [comment]
I have added some clarifying comments in a05a67c9b8935cc8c0774afddfd14defbb3cf64c. I will close this issue when it's merged in.
