### ISSUE TITLE
question: is CCX the spelling error of CXX?

### ISSUE THREAD

**Issue by Alice1069** [LatticeQCD/SIMULATeQCD#75]
in "docs/_sources/01_gettingStarted/gettingStarted.md.txt:- The environment variables `CC` and `CCX` hold the path to the HIP clang compiler"

does here CCX is spelling error of CXX ?

**Comment by lukas-mazur** [comment]
Yes, you are right it should be CXX. That's a type. I will fix that. Thank you!
