### ISSUE TITLE
"mass_s is either not a known parameter..." when run MultiRHSProf on nvidia-cuda-A100

### ISSUE THREAD

**Issue by Alice1069** [LatticeQCD/SIMULATeQCD#79]
I want to build MultiRHSProf and run on nvidia-cuda-A100, but get below errors:
root@4963b223a7bb:/home/alice/hpc/SIMULATeQCD_build_cuda11.4/profiling# mpiexec --allow-run-as-root  -np 1 ./MultiRHSProf
# [2022-04-28 01:27:46] INFO: Initializing MPI with (1 proc)
# [2022-04-28 01:27:46] INFO: Reading parameters from file :: ../parameter/profiling/InverterProfile.param
# [2022-04-28 01:27:46] FATAL: [Rank 0] mass_s is either not a known parameter or its value could not be cast into the correct data type.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] mass_s is either not a known parameter or its value could not be cast into the correct data type.

[4963b223a7bb:00411] *** Process received signal ***
[4963b223a7bb:00411] Signal: Aborted (6)
[4963b223a7bb:00411] Signal code:  (-6)
[4963b223a7bb:00411] [ 0] /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f90e0a583c0]
[4963b223a7bb:00411] [ 1] /usr/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f90e053818b]
[4963b223a7bb:00411] [ 2] /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f90e0517859]
[4963b223a7bb:00411] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9e911)[0x7f90e08ee911]
[4963b223a7bb:00411] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa38c)[0x7f90e08fa38c]
[4963b223a7bb:00411] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa3f7)[0x7f90e08fa3f7]
[4963b223a7bb:00411] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa6a9)[0x7f90e08fa6a9]
[4963b223a7bb:00411] [ 7] ./MultiRHSProf(+0x25037)[0x563ce9c09037]
[4963b223a7bb:00411] [ 8] ./MultiRHSProf(+0xac6561)[0x563cea6aa561]
[4963b223a7bb:00411] [ 9] ./MultiRHSProf(+0x25d77)[0x563ce9c09d77]
[4963b223a7bb:00411] [10] /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f90e05190b3]
[4963b223a7bb:00411] [11] ./MultiRHSProf(+0x2a5de)[0x563ce9c0e5de]
[4963b223a7bb:00411] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 0 on node 4963b223a7bb exited on signal 6 (Aborted).

-----------------reproduce steps-------------------------------------------------------------------------------
Hardware: I have 4 nvidia gpu devices, device 0 is A100-40GB, device 1 is A100-80GB.
OS: Ubuntu 20.04
Software: nvidia official docker release tensorrt:21.10-py3 (cuda 11.4)
SIMULATeQCD code: branch: main; commit id: 8d3d5629eaaa3fb36fdc905ec5daa5b264073da0 (2022,Apr,21th)

cmake ../SIMULATeQCD/ \
-DARCHITECTURE="80" \
-DUSE_GPU_AWARE_MPI=ON \
-DUSE_GPU_P2P=OFF \
-DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda

root@4963b223a7bb:/home/alice/hpc/SIMULATeQCD_build_cuda11.4# make MultiRHSProf
Scanning dependencies of target MultiRHSProf
[  0%] Building CUDA object CMakeFiles/MultiRHSProf.dir/src/profiling/main_MrhsDSlashProf.cpp.o
[  0%] Building CUDA object CMakeFiles/MultiRHSProf.dir/src/modules/dslash/dslash.cpp.o
[  0%] Building CUDA object CMakeFiles/MultiRHSProf.dir/src/modules/HISQ/hisqSmearing.cpp.o
[  0%] Building CUDA object CMakeFiles/MultiRHSProf.dir/src/spinor/spinorfield.cpp.o
[  0%] Building CXX object CMakeFiles/MultiRHSProf.dir/src/base/gutils.cpp.o
[  0%] Building CXX object CMakeFiles/MultiRHSProf.dir/src/base/memoryManagement.cpp.o
[  0%] Building CUDA object CMakeFiles/MultiRHSProf.dir/src/base/indexer/initGPUIndexer.cpp.o
[  0%] Building CXX object CMakeFiles/MultiRHSProf.dir/src/base/indexer/initCPUIndexer.cpp.o
[  0%] Building CXX object CMakeFiles/MultiRHSProf.dir/src/base/communication/communicationBase_mpi.cpp.o
[  0%] Building CXX object CMakeFiles/MultiRHSProf.dir/src/base/IO/parameterManagement.cpp.o
[100%] Building CXX object CMakeFiles/MultiRHSProf.dir/src/base/IO/fileWriter.cpp.o
[100%] Building CUDA object CMakeFiles/MultiRHSProf.dir/src/base/math/grnd.cpp.o
[100%] Building CUDA object CMakeFiles/MultiRHSProf.dir/src/gauge/gaugefield_device.cpp.o
[100%] Building CUDA object CMakeFiles/MultiRHSProf.dir/src/gauge/gaugefield.cpp.o
[100%] Building CUDA object CMakeFiles/MultiRHSProf.dir/src/gauge/GaugeAction.cpp.o
[100%] Building CUDA object CMakeFiles/MultiRHSProf.dir/src/base/LatticeContainer.cpp.o
[100%] Linking CUDA device code CMakeFiles/MultiRHSProf.dir/cmake_device_link.o
[100%] Linking CXX executable profiling/MultiRHSProf
[100%] Built target MultiRHSProf

--------------build is successful, but when run it, I get below error-----------
root@4963b223a7bb:/home/alice/hpc/SIMULATeQCD_build_cuda11.4/profiling# mpiexec --allow-run-as-root  -np 1 ./MultiRHSProf
# [2022-04-28 01:27:46] INFO: Initializing MPI with (1 proc)
# [2022-04-28 01:27:46] INFO: Reading parameters from file :: ../parameter/profiling/InverterProfile.param
# [2022-04-28 01:27:46] FATAL: [Rank 0] mass_s is either not a known parameter or its value could not be cast into the correct data type. .....

------------------------------------------------------------------------------------
I believe nvidia docker image tensorrt21.10-py3 has met the build requirement of cmake/openmp/g++:
root@2d2aa82343c7:/home/alice/hpc/SIMULATeQCD_build_cuda11.4# cmake -version
cmake version 3.14.4
CMake suite maintained and supported by Kitware (kitware.com/cmake).

root@2d2aa82343c7:/home/alice/hpc/SIMULATeQCD_build_cuda11.4# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)  

root@2d2aa82343c7:/home/alice/hpc/SIMULATeQCD_build_cuda11.4# mpiexec --version
mpiexec (OpenRTE) 4.1.2a1
Report bugs to http://www.open-mpi.org/community/help/
------------------------------------------------------------------

also tried cuda 11.0 and latest SIMULATeQCD code on Apr,28, same error.

could you help to take a look at this issue?

**Comment by lukas-mazur** [comment]
This issue is related to issue #71 . I have fixed it now in #80 . Please pull the last version of the main branch and try it again.

**Comment by Alice1069** [comment]
Thanks a lot!

**Comment by lukas-mazur** [comment]
No problem!
