### ISSUE TITLE
error occurs when Building source with HIP for AMD platforms

### ISSUE THREAD

**Issue by Alice1069** [LatticeQCD/SIMULATeQCD#81]
$ make MultiRHSProf -j 60
[  0%] Building HIPCC object CMakeFiles/MultiRHSProf.dir/src/spinor/MultiRHSProf_generated_spinorfield.cpp.o
...
[100%] Building CXX object CMakeFiles/MultiRHSProf.dir/src/base/IO/fileWriter.cpp.o
/home/gputest/alice/SIMULATeQCD/src/base/communication/communicationBase_mpi.cpp:181:26: error: use of undeclared identifier 'gfx90a'
    if (static_cast<int>(ARCHITECTURE) != gpu_arch) {
                         ^
<command line>:1:22: note: expanded from here
#define ARCHITECTURE gfx90a
                     ^
/home/gputest/alice/SIMULATeQCD/src/base/communication/communicationBase_mpi.cpp:182:84: error: use of undeclared identifier 'gfx90a'
        throw std::runtime_error(stdLogger.fatal("You compiled for ARCHITECTURE=", ARCHITECTURE,
                                                                                   ^
<command line>:1:22: note: expanded from here
#define ARCHITECTURE gfx90a
                     ^
2 errors generated when compiling for gfx1030.
make[3]: *** [CMakeFiles/MultiRHSProf.dir/build.make:4483: CMakeFiles/MultiRHSProf.dir/src/base/communication/communicationBase_mpi.cpp.o] Error 1

--------------------------------------------------------------------------------
I guess this error is involved by this commit:
commit 57d3376ea6a1fa53742db41b27dd915be942612d
Author: lukas-mazur <59335056+lukas-mazur@users.noreply.github.com>
Date:   Thu Apr 21 19:53:37 2022 +0200

    Fixed missing ARCHITECTURE definition in CMakelist.txt
------------------------------------------------------------------------------
previous the build is successful with below commit:
commit 8d3d5629eaaa3fb36fdc905ec5daa5b264073da0
Merge: 9a49cc9 2f25242
Author: lukas-mazur <59335056+lukas-mazur@users.noreply.github.com>
Date:   Thu Apr 21 09:12:06 2022 +0200

    Merge pull request #72 from LatticeQCD/Hai-Tao.Shu

    Hai tao.shu

--------additional information about my make file-------------------------------------------------------------------------
$cat 1_make.sh
export HIP_PATH=/opt/rocm/hip
export CC=/opt/rocm/llvm/bin/clang
export CXX=/opt/rocm/llvm/bin/clang++

CXX=hipcc \
cmake ../SIMULATeQCD/ \
-DARCHITECTURE="gfx90a" \
-DUSE_GPU_AWARE_MPI=ON \
-DUSE_GPU_P2P=OFF \
-DBACKEND="hip_amd" \
-DMPI_CXX_COMPILER=/home/gputest/alice/openmpi/bin/mpicxx \
-DMPI_C_COMPILER=/home/gputest/alice/openmpi/bin/mpicc

 ./1_make.sh
-- Using HIP backend for AMD GPUs. (Experimental!)
-- hip::amdhip64 is SHARED_LIBRARY
-- hip::amdhip64 is SHARED_LIBRARY
-- HIP (AMD) Architecture: gfx90a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gputest/alice/SIMULATeQCD_build2

**Comment by lukas-mazur** [comment]
Indeed there was a bug. I have pushed some changes to the main branch which should fix this error (01a0c7170cae7eec4652ee6c24af903a8a676725). 
However, right now I have no running AMD GPU on which I could test it. Please let me know if this works or not.

**Comment by Alice1069** [comment]
yes, the compiling error has been fixed.

**Comment by lukas-mazur** [comment]
Great!
