### ISSUE TITLE
Add a log level for results

### ISSUE THREAD

**Issue by luhuhis** [LatticeQCD/SIMULATeQCD#93]
For tests and for applications like CheckConf and CheckRand it would be nice to have a loglevel between INFO and WARN, for example RESULT. That way one can easily filter for the result of the test/check or even set the loglevel such that only the result or possible errors are printed.

https://github.com/LatticeQCD/SIMULATeQCD/blob/2813b9f37f780bd67469b895f2acaae57dae9c08/src/base/IO/logging.h#L20-L22

**Comment by luhuhis** [comment]
For example for CheckConf, this makes the output very concise by controlling the loglevels:

```
# [2022-07-07 13:06:49] INFO: Checking Gaugefile /work/temp/altenkort/conf/hisq/l9628f21b8249m002022m01011/streama/l9628f21b8249m002022m01011a.995
# [2022-07-07 13:09:10] RESULT: Gaugefile OK! (readin, plaquette, unitarity)
```

**Comment by clarkedavida** [comment]
I guess there are two ways of looking at this, and I don't have a strong feeling either way.

On the one hand, it's also not hard to search for "Gaugefile OK!" or whatever result you are expecting. One also then has to decide sometimes whether something is more of an "INFO" or a "RESULT".

On the other hand, it would be convenient to be able to do something like "filter log file for all results". 

Either way I guess it's not that important, I would rather that you write some documentation :D

**Comment by clarkedavida** [comment]
Ah I see, that's a good point

**Comment by clarkedavida** [comment]
i don't know if anyone is going to do this, and i don't think there is any demand for it.

i want to close this issue, and i will if i don't hear anything after a couple of weeks.
